FROM golang:1.19-alpine AS builder

WORKDIR /

COPY . .

# delve 설치
RUN go install github.com/go-delve/delve/cmd/dlv@latest
# RUN CGO_ENABLED=0 go build -gcflags "all=-N -l" -o ./app

FROM scratch
COPY --from=builder /go/bin/dlv /dlv
# COPY --from=builder /app /app
ENTRYPOINT [ "/dlv" ]