docker-build-debug:
	docker build -f ./docker/debug/Dockerfile.debug --tag go-debug .
docker-run-debug:
	docker-compose -f ./docker/debug/docker-compose-debug.yml up
docker-compose-down-debug:
	docker-compose -f ./docker/debug/docker-compose-debug.yml down
docker-build-test:
	docker build -f ./docker/debug/Dockerfile.test --tag go-test .